apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        selector: mongo
    spec:
      containers:
      - name: mongo
        image:  mongo:5.0.5
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password
        volumeMounts:
        - mountPath: /data
          name: mongo-data
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
      labels:
        env: dev
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ondat-replicated
      resources:
        requests:
          storage: 1Gi